version: '3'

services:
  ngo:
    platform: linux/amd64
    container_name: ngo
    shm_size: '256mb'
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    tty: true
    volumes:
      - .:/go/src

  precommit:
    container_name: precommit
    image: alpine:latest
    volumes:
      - .:/app
    working_dir: /app
    command: cp pre-commit .git/hooks/pre-commit
