name: clockin

on:
  push:
    branches:
      - "main"
  # schedule:
  #   - cron: '45 8 * * 1-5'

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker
        run: |
          make build
          make upd
          echo "${{ secrets.CONFIGYML }}" >> config.yml
          cp config.yml ./bin/
          docker-compose exec -T ngo GOOS=linux go build -ldflags="-s -w" -o ./bin/ndeio cmd/nde-clock-io/main.go

      - name: check holiday
        run: |
          wget https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv
          date "+%Y/%m/%d"
          grep `date "+%Y/%m/%d"`, syukujitsu.csv > /dev/null || docker-compose exec -T ngo ./bin/ndeio clockin
