name: clockout

on:
  schedule:
    - cron: '32 9 * * 1-5'
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm install
        run: npm install @holiday-jp/holiday_jp

      - name: check holiday
        uses: actions/github-script@v3
        id: is_holiday
        with:
          script: |
            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`)
            core.setOutput('holiday', holiday_jp.isHoliday(new Date()));

      - name: run docker
        if: "${{ steps.is_holiday.outputs.holiday != 'true' }}"
        run: |
          make build
          make upd
          echo "${{ secrets.CONFIGYML }}" >> config.yml
          make gobuild

      - name: run
        if: "${{ steps.is_holiday.outputs.holiday != 'true' }}"
        run: |
          echo "stop"
          # docker-compose exec -T ngo ./bin/ndeio clockout
