name: clockin

on:
  push:
    branches:
      - "main"
  # schedule:
  #   - cron: '45 8 * * 1-5'

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker
        run: |
          make build
          make upd
          echo "${{ secrets.CONFIGYML }}" >> config.yml
          make gobuild

      - name: check holiday and run
        run: |
          wget https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv
          grep `date "+%Y/%-m/%-d"`, syukujitsu.csv > /dev/null || docker-compose exec -T ngo ./bin/ndeio clockin
