name: clockin

on:
  # schedule:
  #   - cron: '45 23 * * 0-4'
  push:
    branches:
      - "main"

env:
  TZ: 'Asia/Tokyo'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run docker
        run: |
          make build
          make upd
          echo "${{ secrets.CONFIGYML }}" >> config.yml
          make gobuild

      - name: check holiday and run
        run: |
          wget https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv
          CHECK=$(grep -a `date "+%Y/%-m/%-d"`, syukujitsu.csv)
          if [ -z "$CHECK" ]; then
            echo 'test';
            # docker-compose exec -T ngo ./bin/ndeio clockin;
          fi
